### ISSUE TITLE
Is compilation buffer in comint mode on purpose?

### ISSUE THREAD

**Issue by laurynas-biveinis** [rpav/cmake-build.el#13]
Regular `M-x compile` creates a non-comint, that is, non-interactive compilation buffer. `C-u M-x compile` creates a comint one, i.e. where input is possible too.
cmake-build.el always sets up the latter - comint compile, is it on purpose?

One practical difference between the two is that `compilation-filter` defun and associated `compilation-filter-hook` do not get called in comint mode.

If it's not on purpose, please consider using regular compile instead:
```
modified   cmake-build.el
@@ -278,7 +278,7 @@ use Projectile to determine the root on a buffer-local basis, instead.")
                  (symbol-name cmake-build-profile))
       ;; compile saves buffers; rely on this now
       (let* ((compilation-buffer-name-function #'cmake-build--build-buffer-name))
-        (cl-flet ((run-compile () (compile (concat "time " command) t)))
+        (cl-flet ((run-compile () (compile (concat "time " command))))
           (let ((w (get-buffer-window buffer-name t)))
             (if (and w (not (eql (get-buffer-window) w)))
                 (if cmake-build-switch-to-build

```

**Comment by rpav** [comment]
Yes, because I want to be able to push `C-c C-c` and kill the compile. ;)

**Comment by laurynas-biveinis** [comment]
I guess you are not looking to use the (global - works from any buffer) `C-c C-k` binding of `kill-compilation`? :)

**Comment by rpav** [comment]
I probably should eh?

What does the `compilation-filter` do exactly?  It wasn't clear from a quick glance at the code or trying to find documentation on the issue; I didn't notice a difference in output ... but maybe I wasn't looking terribly closely.

**Comment by rpav** [comment]
Err, also not using comint seems to break auto scrolling, which is considerably annoying.

**Comment by laurynas-biveinis** [comment]
Yes if you ask me :) `C-c C-k` also kills running grep

[I use](https://github.com/laurynas-biveinis/dotfiles/blob/master/emacs/emacs/setup.el#L444) compilation-filter for colors (it is colors which led me down this rabbit hole, I was getting raw escape sequences in the output):
```elisp
(setq compilation-environment '("LANG=C" "TERM=xterm-256color"))

(require 'xterm-color)
(defun dotfiles--compilation-filter-advice (f proc string)
  "Compilation filter for xterm-256color, taking F, PROC, & STRING."
  (funcall f proc (xterm-color-filter string)))

(advice-add #'compilation-filter :around #'dotfiles--compilation-filter-advice)
```
As for scrolling, it's a different code path, so different customisation variable - one of the  `compilation-scroll-output` values should work for you

**Comment by rpav** [comment]
My `compilation-scroll-output` is `t` .. still doesn't scroll.  This seems to be a common issue when not manually calling `M-x compile` and no definitive resolution.

**Comment by laurynas-biveinis** [comment]
Ah, I didn't know that, I use 'first-error. 

Would a customisation variable to comint or not comint work?

**Comment by rpav** [comment]
Does any setting scroll for you?  (I.e. remove the `t` in `run-compile` and try..)  Either fails for me; if it works for you then clearly *something* must lead to correct behavior.

I can certainly make this a setting, but if output scrolling can be fixed it would be even more beneficial.  There is probably little reason to use comint in that case.

**Comment by laurynas-biveinis** [comment]
Yes, it scrolls as expected with 'first-error without t in run-compile

**Comment by rpav** [comment]
I'll have to look into this further... what platform/version/etc are you on?  This is Linux, on a recent 28.0.50 build, though I doubt that has much to do with it.

**Comment by laurynas-biveinis** [comment]
26.3 https://emacsformacosx.com

**Comment by rpav** [comment]
OK, this *seems* to have fixed things.  Multiple emacs restarts and it still seems to work.

Apparently somewhere along the way, or at least for some platforms (?), the window-point and point are different, and/or `window-point-insertion-type` is set to `nil` in the wrong places: I don't know.  The `(set-window-position ..)` may need moved higher if it breaks `first-error`, but I'm not sure.

**Comment by laurynas-biveinis** [comment]
Closing as fixed, thank you
