### ISSUE TITLE
Symlink compile-commands.json automatically

### ISSUE THREAD

**Issue by laurynas-biveinis** [rpav/cmake-build.el#18]
If CMake is configured with `CMAKE_EXPORT_COMPILE_COMMANDS`, then it will produce compile_commands.json in the build directory. If Emacs is configured with LSP support, e.g. with clangd, then opening a C or C++ file in the project will start the language server, which will look for compile_commands.json in the same directory (and not find it since it's in the build dir).

If cmake-build.el symlinked compile_commands.json from the build dir to the source dir on `cmake-build-set-cmake-profile` invocations, then we'd have a seamless LSP/cmake-build.el integration.

**Comment by dlyr** [comment]
I have a proposal (with other "improvements" for my usage) on [my fork.](https://github.com/dlyr/cmake-build.el/tree/wip)

check in particular [this commit](https://github.com/dlyr/cmake-build.el/commit/1fc433ed61aea9ea6015470f9d0efcf88c0b2fd1)

The link is set on configure (since profile setup is not sufficient as far as I know, you need to run cmake to have the file).
If needed I restart lsp (I use ccls, and the compile_commands.json is read only at startup).

**Comment by laurynas-biveinis** [comment]
@dlyr nice! Are there plans to merge your improvements back?

**Comment by dlyr** [comment]
@laurynas-biveinis I've made a PR, could be cool if you can test and confirm it works for you as expected.

**Comment by laurynas-biveinis** [comment]
@dlyr, thank you for the PR! I will test it in my daily use

@rpav, for some reason I cannot comment on the PR, so I'll do it here: re. objections, my 2c - this is extremely useful in the general case, as it would provide nearly perfect out-of-the-box experience for small to medium projects where CDB postprocessing issues simply do not arise. I also believe it's fine to have a CDB for each configuration and repoint the symlink on each CMake profile switch - it would give precise LSP experience on i.e. debug vs release builds.

**Comment by rpav** [comment]
I'd be happy to merge the patch if someone fixed the noted issues and/or I get time to... just a few defcustom, some checks, and documentation.

**Comment by dlyr** [comment]
Fair for me, I'll could do it within next couple of days

**Comment by laurynas-biveinis** [comment]
@dlyr, your PR works great as expected in my testing. I have left one minor suggestion on relative vs absolute symlink on the PR. Thanks again,
