### ISSUE TITLE
cmake-build-options.el not persistent

### ISSUE THREAD

**Issue by dlyr** [rpav/cmake-build.el#2]
Hi,
If I understand well, I can set some persistent local (to my computer) options in the file `~/emacs.config.dir.d./cmake-build-options.el`
This file was created the fist time I open a project after cmake-build installation.
I set some variable, ie replace `(:build-options "")` by `(:build-options "-j4"), save and quit emacs.
But this is not taken into account, and overwritten when I close emacs after having a project open.

**Comment by rpav** [comment]
Oh, this is a bit like `custom` stuff and not intended to be edited manually, rather it stores all the machine-local interactive values.  In this case, use `M-x cmake-build-set-options` to change/save the cmake build options.
